language: php

php:
  - 5.5
  - 5.6
  - 7

env:
  matrix:
    - REQUIRE_VERSION="'dev-WIP-remove-identity-provider as 3.0'"
    - REQUIRE_VERSION="'^2.5.2'"

before_script:
  - composer self-update
  - composer require $REQUIRE_VERSION

before_script:
  - composer self-update
  - composer update

script:
  - php ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

after_script:
  - php vendor/bin/coveralls -v

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
